// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBcI9czTHkweFOIGHaC312Dx1sxgG-DQM',
    appId: '1:718059480954:web:1dae4bac820bb8161a18c3',
    messagingSenderId: '718059480954',
    projectId: 'econnect-final',
    authDomain: 'econnect-final.firebaseapp.com',
    storageBucket: 'econnect-final.firebasestorage.app',
    measurementId: 'G-K9G5K7LBX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyComs4rdKkpGtGthuMGORzm6tiOmsaM4gg',
    appId: '1:718059480954:android:4649b45f7a0bbca71a18c3',
    messagingSenderId: '718059480954',
    projectId: 'econnect-final',
    storageBucket: 'econnect-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4WtzoOar9I8B3yI8GBJwfkIimxCrghjE',
    appId: '1:718059480954:ios:ee7aa36fa0b988531a18c3',
    messagingSenderId: '718059480954',
    projectId: 'econnect-final',
    storageBucket: 'econnect-final.firebasestorage.app',
    iosBundleId: 'com.yourcompany.econnectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4WtzoOar9I8B3yI8GBJwfkIimxCrghjE',
    appId: '1:718059480954:ios:ee7aa36fa0b988531a18c3',
    messagingSenderId: '718059480954',
    projectId: 'econnect-final',
    storageBucket: 'econnect-final.firebasestorage.app',
    iosBundleId: 'com.yourcompany.econnectFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBcI9czTHkweFOIGHaC312Dx1sxgG-DQM',
    appId: '1:718059480954:web:4f0a6ad8ccf991bc1a18c3',
    messagingSenderId: '718059480954',
    projectId: 'econnect-final',
    authDomain: 'econnect-final.firebaseapp.com',
    storageBucket: 'econnect-final.firebasestorage.app',
    measurementId: 'G-BFBDK6ZCQ7',
  );
}
